version: '3.8'

services:
  content_generator:
    build:
      context: .
      dockerfile: dockerfile
    container_name: parsllm
    restart: always
    volumes:
      - /etc/letsencrypt/live/parsllm.ir/fullchain.pem:/etc/letsencrypt/live/parsllm.ir/fullchain.pem
      - /etc/letsencrypt/live/parsllm.ir/privkey.pem:/etc/letsencrypt/live/parsllm.ir/privkey.pem
    ports:
      - "443:443"
