version: '3.8'

services:
  content_generator:
    build:
      context: .
      dockerfile: dockerfile
    container_name: parsllm
    restart: always
    volumes:
      - /etc/letsencrypt/live/parsllm.ir/fullchain.pem:/etc/letsencrypt/live/parsllm.ir/fullchain.pem
      - /etc/letsencrypt/live/parsllm.ir/privkey.pem:/etc/letsencrypt/live/parsllm.ir/privkey.pem
    ports:
      - "443:443"
    networks:
      - webnet


  db:
    image: postgres:latest
    volumes:
      - /home/devops8968/psql/data:/var/lib/postgresql/data
      - /home/devops8968/psql/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - webnet

networks:
  webnet:

